[package]
name = "mtn_demo_img"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "bmp", "gif", "tiff", "webp"] }
serde_json = "1"

[profile.release]
panic = "abort"
lto = true
opt-level = 3
codegen-units = 1
